language: python
cache: pip
python:
 - "3.4"
git:
  depth: 3
branches:
  except:
    - experimental
install:
  - pip install tox
env:
  - TOXENV=flake8
  - TOXENV=unittests
script:
  - tox -e $TOX_ENV
