site_name: Mau Mau
pages:
  - Home: index.md
  - User Guide:
    - Rules of the game: guide/rules.md
    - Command line usage: guide/usage.md
  - Development:
    - Implementation: dev/implementation.md
    - Explore the code: dev/explore.md
    - Remarks: dev/remarks.md
#theme: readthedocs
site_dir: docs/_build
repo_url: https://github.com/obestwalter/mau-mau
strict: True
