theme: readthedocs
site_name: Mau Mau

pages:
  - Home: index.md
  - User Guide:
    - Rules of the game: guide/rules.md
    - Command line usage: guide/usage.md
  - Development:
    - Implementation: dev/implementation.md
    - Explore the code: dev/explore.md
    - Things to point out: dev/remarks.md


site_dir: docs/_build

repo_url: https://github.com/obestwalter/mau-mau

strict: True

markdown_extensions:
    - toc:
        permalink: 
